### ISSUE TITLE
FR - Fullscreen option

### ISSUE THREAD

**Issue by DusteDdk** [vsergeev/audioprism#2]
It'd be cool if one could do --fullscreen (maybe with an optional screen-number).
I may implement this but at the moment, I don't have the time :(

Ps: This is a super cool project, thanks for making it!

**Comment by vsergeev** [comment]
Yeah, that would be cool. It should be pretty easy to implement with a resolution query and the `SDL_WINDOW_FULLSCREEN` flag to `SDL_CreateWindow()`.
