### ISSUE TITLE
[Arch Linux] No spectrogram output

### ISSUE THREAD

**Issue by parkerlreed** [vsergeev/audioprism#4]
I have my monitor set as default but nothing is displaying in the audioprism window.

libpulse 12.0-1
fftw 3.3.8-1
sdl2 2.0.8-8
sdl2_ttf 2.0.14-1
libsndfile 1.0.28-1
graphicsmagick 1.3.30-1
audioprism 1.0.1-1

![screenshot_20180707_165245](https://user-images.githubusercontent.com/841440/42414609-6be96b5e-8206-11e8-8085-2ee2d49a8c9a.png)

**Comment by vsergeev** [comment]
I think you may have just had the wrong tab -- the stream selection for applications will be under the "Recording" tab:

![pulseaudio](https://user-images.githubusercontent.com/524033/76384484-02361b80-632d-11ea-8274-838892e051f2.png)

Closing for now, feel free to re-open if there is still an issue.

**Comment by parkerlreed** [comment]
Ahh thanks. Yep that works.
